[package]
name = "euler-rust"
version = "0.1.0"
authors = ["Alexander Gude <alex.public.account+ProjectEulerSolutions@gmail.com>"]
edition = "2021"

[dependencies]
# Used in 013.rs (BigUint)
num = "0.4"
